# Generated by Django 5.1.4 on 2026-06-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_age_user_country_of_origin_user_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
