# Generated by Django 5.1.4 on 2026-06-25 00:55

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('age', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
                ('place_of_living', models.CharField(max_length=120)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('undisclosed', 'Prefer not to say')], max_length=12)),
                ('country_of_origin', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('photo_key', models.CharField(max_length=255)),
                ('photo_content_type', models.CharField(default='image/jpeg', max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('failed', 'Failed'), ('rejected', 'Rejected (safety)')], default='pending', max_length=12)),
                ('classification_result', models.JSONField(blank=True, null=True)),
                ('error_detail', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['age'], name='sub_age_idx'), models.Index(fields=['gender'], name='sub_gender_idx'), models.Index(fields=['country_of_origin'], name='sub_country_idx'), models.Index(fields=['place_of_living'], name='sub_place_idx'), models.Index(fields=['created_at'], name='sub_created_idx'), models.Index(fields=['status'], name='sub_status_idx'), models.Index(fields=['gender', 'country_of_origin', 'age'], name='sub_gender_country_age_idx')],
            },
        ),
    ]
