# Generated by Django 5.1.4 on 2026-06-26 08:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='consistency',
            field=models.CharField(choices=[('pending', 'Pending'), ('consistent', 'Consistent'), ('inconsistent', 'Inconsistent'), ('unverified', 'Unverified')], default='pending', max_length=12),
        ),
        migrations.AddField(
            model_name='submission',
            name='verification',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['consistency'], name='sub_consistency_idx'),
        ),
    ]
